language: node_js
node_js:
    - 9

script:
    - cd webapp
    - yar install
    - yarn run build
    - yarn run lint
    - yarn test
    - cd ../backend
    - yarn install
    - yarn run lint
    - yarn test
