language: node_js
node_js:
    - 9

# credit to aradar / NoraAnlima for config inspiration
install:
    - yarn --cwd ./webapp install
    - yarn --cwd ./backend install

script:
    - yarn --cwd ./webapp run build
    - yarn --cwd ./webapp run lint
    - yarn --cwd ./webapp run test
    - yarn --cwd ./webapp install
    - yarn --cwd ./webapp run lint
    - yarn --cwd ./webapp test
