language: node_js

node_js:
    - "stable"

services:
    - docker

before_install:
    - curl -v POST http://neo4j:neo4j@localhost:7474/user/neo4j/password -d"password=wordpass2"
    - curl -v POST http://neo4j:wordpass2@localhost:7474/user/neo4j/password -d"password=wordpass"

# credit to aradar / NoraAnlima for config inspiration
install:
    - yarn --cwd ./webapp install
    - yarn --cwd ./backend install

script:
    - node ./backend/helper/seed_db.js
    - yarn --cwd ./webapp run build
    - yarn --cwd ./webapp run lint
    - yarn --cwd ./webapp run test
    - yarn --cwd ./backend run lint
    - yarn --cwd ./backend test
