env:
  browser: true
  es6: true
  jest: true
  amd: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  allowImportExportEverywhere: true
plugins:
  - vue
rules: {
  require-atomic-updates: 'off'
}
